### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by EliRibble** [MisterTea/TidalWave#1]
I heard about this wiki on the show and was curious to see how hard it would be to set up. Can you add some instructions on how to get it installed? Ideally instructions that are more generic than heroku.

**Comment by MisterTea** [comment]
I added instructions to the readme, please check it out and let me know if it explains how to roll a server:

https://github.com/MisterTea/TidalWave/blob/master/README.md

**Comment by EliRibble** [comment]
Looks good, I'll have to give installation a try. Thanks!
