### ISSUE TITLE
Heroku demo is down

### ISSUE THREAD

**Issue by EliRibble** [MisterTea/TidalWave#2]
You might want to take a look at the heroku demo - the page linked from the show notes/READ, http://tidalwave-demo.herokuapp.com/view#/Welcome, doesn't work at all. It just says:

An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.

**Comment by MisterTea** [comment]
It's back up now, thanks for letting me know.
